# dbt profiles configuration for local PostgreSQL development

ecommerce_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: dbt_user
      password: dbt_password
      dbname: ecommerce_dw
      schema: analytics_dev
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      search_path: analytics_dev,public

    prod:
      type: postgres
      host: "{{ env_var('DBT_PROD_HOST', 'localhost') }}"
      port: "{{ env_var('DBT_PROD_PORT', '5432') }}"
      user: "{{ env_var('DBT_PROD_USER', 'dbt_user') }}"
      password: "{{ env_var('DBT_PROD_PASSWORD', 'dbt_password') }}"
      dbname: "{{ env_var('DBT_PROD_DB', 'ecommerce_dw') }}"
      schema: analytics_prod
      threads: 8
      keepalives_idle: 0
      connect_timeout: 10
